version: 0.0
os: linux
files:
  - source: ./build
    destination: /home/2023-1-Team3/frontend/build
hooks:
  AfterInstall:
    - location: scripts/start_server
      timeout: 300
      runas: ubuntu
