version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/repo
    overwrite: yes
permissions:
  - object: /home/ubuntu/repo
    owner: ubuntu
    group: ubuntu
    mode: 755

hooks:
  AfterInstall:
    - location: scripts/stop_server
      timeout: 60
      runas: root
